---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      become: true
      apt: name=nginx state=latest
    - name: start nginx
      become: true
      service:
          name: nginx
          state: started
